/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


enum RESOURCE_TYPE {
  RESOURCE_TYPE_SONG = 1,
  RESOURCE_TYPE_CARTOON = 2,
  RESOURCE_TYPE_TV = 3,
  RESOURCE_TYPE_SEARCH_RECOMMEND = 4,
  RESOURCE_TYPE_RESOURCE_TYPE_NUM = 5
};

enum RESOURCE_STATUS {
  RESOURCE_STATUS_NORMAL = 0,
  RESOURCE_STATUS_RECOMMEND = 1,
  RESOURCE_STATUS_HOT = 2,
  RESOURCE_STATUS_BAD = 3,
  RESOURCE_STATUS_RESOURCE_STATUS_NUM = 4
};

enum RESOURCE_SOURCE_TYPE {
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_YOUKU = 0,
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_56 = 1,
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_SOHU = 2,
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_CNTV = 3,
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_SHY = 4,
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_NUM = 5
};

@interface ReqHead : NSObject <TBase, NSCoding> {
  int32_t __babyId;
  NSString * __guid;
  NSString * __version;

  BOOL __babyId_isset;
  BOOL __guid_isset;
  BOOL __version_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=babyId, setter=setBabyId:) int32_t babyId;
@property (nonatomic, retain, getter=guid, setter=setGuid:) NSString * guid;
@property (nonatomic, retain, getter=version, setter=setVersion:) NSString * version;
#endif

- (id) init;
- (id) initWithBabyId: (int32_t) babyId guid: (NSString *) guid version: (NSString *) version;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) babyId;
- (void) setBabyId: (int32_t) babyId;
#endif
- (BOOL) babyIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) guid;
- (void) setGuid: (NSString *) guid;
#endif
- (BOOL) guidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) version;
- (void) setVersion: (NSString *) version;
#endif
- (BOOL) versionIsSet;

@end

@interface RegisterResp : NSObject <TBase, NSCoding> {
  int32_t __babyId;
  NSString * __pwd;
  int32_t __resCode;

  BOOL __babyId_isset;
  BOOL __pwd_isset;
  BOOL __resCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=babyId, setter=setBabyId:) int32_t babyId;
@property (nonatomic, retain, getter=pwd, setter=setPwd:) NSString * pwd;
@property (nonatomic, getter=resCode, setter=setResCode:) int32_t resCode;
#endif

- (id) init;
- (id) initWithBabyId: (int32_t) babyId pwd: (NSString *) pwd resCode: (int32_t) resCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) babyId;
- (void) setBabyId: (int32_t) babyId;
#endif
- (BOOL) babyIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pwd;
- (void) setPwd: (NSString *) pwd;
#endif
- (BOOL) pwdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) resCode;
- (void) setResCode: (int32_t) resCode;
#endif
- (BOOL) resCodeIsSet;

@end

@interface LoginReq : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSString * __authStr;

  BOOL __head_isset;
  BOOL __authStr_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=authStr, setter=setAuthStr:) NSString * authStr;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head authStr: (NSString *) authStr;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSString *) authStr;
- (void) setAuthStr: (NSString *) authStr;
#endif
- (BOOL) authStrIsSet;

@end

@interface UserConfig : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSString * __appKey56;
  int32_t __reportFlag;
  int32_t __searchKeysVer;
  int32_t __searchImgVer;

  BOOL __head_isset;
  BOOL __appKey56_isset;
  BOOL __reportFlag_isset;
  BOOL __searchKeysVer_isset;
  BOOL __searchImgVer_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=appKey56, setter=setAppKey56:) NSString * appKey56;
@property (nonatomic, getter=reportFlag, setter=setReportFlag:) int32_t reportFlag;
@property (nonatomic, getter=searchKeysVer, setter=setSearchKeysVer:) int32_t searchKeysVer;
@property (nonatomic, getter=searchImgVer, setter=setSearchImgVer:) int32_t searchImgVer;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head appKey56: (NSString *) appKey56 reportFlag: (int32_t) reportFlag searchKeysVer: (int32_t) searchKeysVer searchImgVer: (int32_t) searchImgVer;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSString *) appKey56;
- (void) setAppKey56: (NSString *) appKey56;
#endif
- (BOOL) appKey56IsSet;

#if !__has_feature(objc_arc)
- (int32_t) reportFlag;
- (void) setReportFlag: (int32_t) reportFlag;
#endif
- (BOOL) reportFlagIsSet;

#if !__has_feature(objc_arc)
- (int32_t) searchKeysVer;
- (void) setSearchKeysVer: (int32_t) searchKeysVer;
#endif
- (BOOL) searchKeysVerIsSet;

#if !__has_feature(objc_arc)
- (int32_t) searchImgVer;
- (void) setSearchImgVer: (int32_t) searchImgVer;
#endif
- (BOOL) searchImgVerIsSet;

@end

@interface SearchSuggestKeys : NSObject <TBase, NSCoding> {
  int32_t __version;
  NSString * __suggestKeys;

  BOOL __version_isset;
  BOOL __suggestKeys_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=version, setter=setVersion:) int32_t version;
@property (nonatomic, retain, getter=suggestKeys, setter=setSuggestKeys:) NSString * suggestKeys;
#endif

- (id) init;
- (id) initWithVersion: (int32_t) version suggestKeys: (NSString *) suggestKeys;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) version;
- (void) setVersion: (int32_t) version;
#endif
- (BOOL) versionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) suggestKeys;
- (void) setSuggestKeys: (NSString *) suggestKeys;
#endif
- (BOOL) suggestKeysIsSet;

@end

@interface ResourceInfo : NSObject <TBase, NSCoding> {
  int32_t __shyId;
  NSString * __url;
  NSString * __img;
  NSString * __title;
  int __sourceType;
  int __resourceType;
  int32_t __durationTime;
  int __status;
  int32_t __curSection;
  int32_t __sectionNum;
  NSString * __serialId;
  NSString * __vid;
  NSString * __serialDes;
  NSString * __serialName;

  BOOL __shyId_isset;
  BOOL __url_isset;
  BOOL __img_isset;
  BOOL __title_isset;
  BOOL __sourceType_isset;
  BOOL __resourceType_isset;
  BOOL __durationTime_isset;
  BOOL __status_isset;
  BOOL __curSection_isset;
  BOOL __sectionNum_isset;
  BOOL __serialId_isset;
  BOOL __vid_isset;
  BOOL __serialDes_isset;
  BOOL __serialName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=shyId, setter=setShyId:) int32_t shyId;
@property (nonatomic, retain, getter=url, setter=setUrl:) NSString * url;
@property (nonatomic, retain, getter=img, setter=setImg:) NSString * img;
@property (nonatomic, retain, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, getter=sourceType, setter=setSourceType:) int sourceType;
@property (nonatomic, getter=resourceType, setter=setResourceType:) int resourceType;
@property (nonatomic, getter=durationTime, setter=setDurationTime:) int32_t durationTime;
@property (nonatomic, getter=status, setter=setStatus:) int status;
@property (nonatomic, getter=curSection, setter=setCurSection:) int32_t curSection;
@property (nonatomic, getter=sectionNum, setter=setSectionNum:) int32_t sectionNum;
@property (nonatomic, retain, getter=serialId, setter=setSerialId:) NSString * serialId;
@property (nonatomic, retain, getter=vid, setter=setVid:) NSString * vid;
@property (nonatomic, retain, getter=serialDes, setter=setSerialDes:) NSString * serialDes;
@property (nonatomic, retain, getter=serialName, setter=setSerialName:) NSString * serialName;
#endif

- (id) init;
- (id) initWithShyId: (int32_t) shyId url: (NSString *) url img: (NSString *) img title: (NSString *) title sourceType: (int) sourceType resourceType: (int) resourceType durationTime: (int32_t) durationTime status: (int) status curSection: (int32_t) curSection sectionNum: (int32_t) sectionNum serialId: (NSString *) serialId vid: (NSString *) vid serialDes: (NSString *) serialDes serialName: (NSString *) serialName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) shyId;
- (void) setShyId: (int32_t) shyId;
#endif
- (BOOL) shyIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) url;
- (void) setUrl: (NSString *) url;
#endif
- (BOOL) urlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) img;
- (void) setImg: (NSString *) img;
#endif
- (BOOL) imgIsSet;

#if !__has_feature(objc_arc)
- (NSString *) title;
- (void) setTitle: (NSString *) title;
#endif
- (BOOL) titleIsSet;

#if !__has_feature(objc_arc)
- (int) sourceType;
- (void) setSourceType: (int) sourceType;
#endif
- (BOOL) sourceTypeIsSet;

#if !__has_feature(objc_arc)
- (int) resourceType;
- (void) setResourceType: (int) resourceType;
#endif
- (BOOL) resourceTypeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) durationTime;
- (void) setDurationTime: (int32_t) durationTime;
#endif
- (BOOL) durationTimeIsSet;

#if !__has_feature(objc_arc)
- (int) status;
- (void) setStatus: (int) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (int32_t) curSection;
- (void) setCurSection: (int32_t) curSection;
#endif
- (BOOL) curSectionIsSet;

#if !__has_feature(objc_arc)
- (int32_t) sectionNum;
- (void) setSectionNum: (int32_t) sectionNum;
#endif
- (BOOL) sectionNumIsSet;

#if !__has_feature(objc_arc)
- (NSString *) serialId;
- (void) setSerialId: (NSString *) serialId;
#endif
- (BOOL) serialIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) vid;
- (void) setVid: (NSString *) vid;
#endif
- (BOOL) vidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) serialDes;
- (void) setSerialDes: (NSString *) serialDes;
#endif
- (BOOL) serialDesIsSet;

#if !__has_feature(objc_arc)
- (NSString *) serialName;
- (void) setSerialName: (NSString *) serialName;
#endif
- (BOOL) serialNameIsSet;

@end

@interface ResourceResp : NSObject <TBase, NSCoding> {
  NSMutableArray * __resList;
  int32_t __resCode;

  BOOL __resList_isset;
  BOOL __resCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=resList, setter=setResList:) NSMutableArray * resList;
@property (nonatomic, getter=resCode, setter=setResCode:) int32_t resCode;
#endif

- (id) init;
- (id) initWithResList: (NSMutableArray *) resList resCode: (int32_t) resCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) resList;
- (void) setResList: (NSMutableArray *) resList;
#endif
- (BOOL) resListIsSet;

#if !__has_feature(objc_arc)
- (int32_t) resCode;
- (void) setResCode: (int32_t) resCode;
#endif
- (BOOL) resCodeIsSet;

@end

@interface SearchReq : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSString * __searchKeys;
  int32_t __startId;
  int32_t __recordNum;
  int __resourceType;
  NSString * __serialId;

  BOOL __head_isset;
  BOOL __searchKeys_isset;
  BOOL __startId_isset;
  BOOL __recordNum_isset;
  BOOL __resourceType_isset;
  BOOL __serialId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=searchKeys, setter=setSearchKeys:) NSString * searchKeys;
@property (nonatomic, getter=startId, setter=setStartId:) int32_t startId;
@property (nonatomic, getter=recordNum, setter=setRecordNum:) int32_t recordNum;
@property (nonatomic, getter=resourceType, setter=setResourceType:) int resourceType;
@property (nonatomic, retain, getter=serialId, setter=setSerialId:) NSString * serialId;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head searchKeys: (NSString *) searchKeys startId: (int32_t) startId recordNum: (int32_t) recordNum resourceType: (int) resourceType serialId: (NSString *) serialId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSString *) searchKeys;
- (void) setSearchKeys: (NSString *) searchKeys;
#endif
- (BOOL) searchKeysIsSet;

#if !__has_feature(objc_arc)
- (int32_t) startId;
- (void) setStartId: (int32_t) startId;
#endif
- (BOOL) startIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) recordNum;
- (void) setRecordNum: (int32_t) recordNum;
#endif
- (BOOL) recordNumIsSet;

#if !__has_feature(objc_arc)
- (int) resourceType;
- (void) setResourceType: (int) resourceType;
#endif
- (BOOL) resourceTypeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) serialId;
- (void) setSerialId: (NSString *) serialId;
#endif
- (BOOL) serialIdIsSet;

@end

@interface RecommendReq : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  int32_t __startId;
  int32_t __recordNum;

  BOOL __head_isset;
  BOOL __startId_isset;
  BOOL __recordNum_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, getter=startId, setter=setStartId:) int32_t startId;
@property (nonatomic, getter=recordNum, setter=setRecordNum:) int32_t recordNum;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head startId: (int32_t) startId recordNum: (int32_t) recordNum;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (int32_t) startId;
- (void) setStartId: (int32_t) startId;
#endif
- (BOOL) startIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) recordNum;
- (void) setRecordNum: (int32_t) recordNum;
#endif
- (BOOL) recordNumIsSet;

@end

@interface AlbumReq : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSString * __serialId;
  int32_t __startId;
  int32_t __recordNum;
  NSString * __sectionName;

  BOOL __head_isset;
  BOOL __serialId_isset;
  BOOL __startId_isset;
  BOOL __recordNum_isset;
  BOOL __sectionName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=serialId, setter=setSerialId:) NSString * serialId;
@property (nonatomic, getter=startId, setter=setStartId:) int32_t startId;
@property (nonatomic, getter=recordNum, setter=setRecordNum:) int32_t recordNum;
@property (nonatomic, retain, getter=sectionName, setter=setSectionName:) NSString * sectionName;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head serialId: (NSString *) serialId startId: (int32_t) startId recordNum: (int32_t) recordNum sectionName: (NSString *) sectionName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSString *) serialId;
- (void) setSerialId: (NSString *) serialId;
#endif
- (BOOL) serialIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) startId;
- (void) setStartId: (int32_t) startId;
#endif
- (BOOL) startIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) recordNum;
- (void) setRecordNum: (int32_t) recordNum;
#endif
- (BOOL) recordNumIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sectionName;
- (void) setSectionName: (NSString *) sectionName;
#endif
- (BOOL) sectionNameIsSet;

@end

@interface ResourcesReq : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSString * __title;
  NSString * __serialId;
  int32_t __startId;
  int32_t __recordNum;
  int __resourceType;
  int __sourceType;
  int __status;

  BOOL __head_isset;
  BOOL __title_isset;
  BOOL __serialId_isset;
  BOOL __startId_isset;
  BOOL __recordNum_isset;
  BOOL __resourceType_isset;
  BOOL __sourceType_isset;
  BOOL __status_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, retain, getter=serialId, setter=setSerialId:) NSString * serialId;
@property (nonatomic, getter=startId, setter=setStartId:) int32_t startId;
@property (nonatomic, getter=recordNum, setter=setRecordNum:) int32_t recordNum;
@property (nonatomic, getter=resourceType, setter=setResourceType:) int resourceType;
@property (nonatomic, getter=sourceType, setter=setSourceType:) int sourceType;
@property (nonatomic, getter=status, setter=setStatus:) int status;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head title: (NSString *) title serialId: (NSString *) serialId startId: (int32_t) startId recordNum: (int32_t) recordNum resourceType: (int) resourceType sourceType: (int) sourceType status: (int) status;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSString *) title;
- (void) setTitle: (NSString *) title;
#endif
- (BOOL) titleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) serialId;
- (void) setSerialId: (NSString *) serialId;
#endif
- (BOOL) serialIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) startId;
- (void) setStartId: (int32_t) startId;
#endif
- (BOOL) startIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) recordNum;
- (void) setRecordNum: (int32_t) recordNum;
#endif
- (BOOL) recordNumIsSet;

#if !__has_feature(objc_arc)
- (int) resourceType;
- (void) setResourceType: (int) resourceType;
#endif
- (BOOL) resourceTypeIsSet;

#if !__has_feature(objc_arc)
- (int) sourceType;
- (void) setSourceType: (int) sourceType;
#endif
- (BOOL) sourceTypeIsSet;

#if !__has_feature(objc_arc)
- (int) status;
- (void) setStatus: (int) status;
#endif
- (BOOL) statusIsSet;

@end

@interface ReportReq : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSString * __rptItem;

  BOOL __head_isset;
  BOOL __rptItem_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=rptItem, setter=setRptItem:) NSString * rptItem;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head rptItem: (NSString *) rptItem;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSString *) rptItem;
- (void) setRptItem: (NSString *) rptItem;
#endif
- (BOOL) rptItemIsSet;

@end

@protocol UserManager <NSObject>
- (RegisterResp *) userRegister: (ReqHead *) req;  // throws TException
- (int32_t) login: (LoginReq *) req;  // throws TException
- (NSString *) getAuthSeed: (ReqHead *) req;  // throws TException
- (void) logout: (ReqHead *) req;  // throws TException
- (UserConfig *) updateConfig: (ReqHead *) req;  // throws TException
- (SearchSuggestKeys *) getSearchSuggestKeys: (ReqHead *) req;  // throws TException
@end

@interface UserManagerClient : NSObject <UserManager> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface UserManagerProcessor : NSObject <TProcessor> {
  id <UserManager> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithUserManager: (id <UserManager>) service;
- (id<UserManager>) service;
@end

@protocol ResourceManager <NSObject>
- (ResourceResp *) search: (SearchReq *) req;  // throws TException
- (ResourceResp *) getRecommendSongs: (RecommendReq *) req;  // throws TException
- (ResourceResp *) getRecommendCartoons: (RecommendReq *) req;  // throws TException
- (ResourceResp *) getRecommendTVs: (RecommendReq *) req;  // throws TException
- (ResourceResp *) getAlbum: (AlbumReq *) req;  // throws TException
- (ResourceResp *) getSearchRecommend: (ReqHead *) req;  // throws TException
@end

@interface ResourceManagerClient : NSObject <ResourceManager> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ResourceManagerProcessor : NSObject <TProcessor> {
id <ResourceManager> mService;
NSDictionary * mMethodMap;
}
- (id) initWithResourceManager: (id <ResourceManager>) service;
- (id<ResourceManager>) service;
@end

@protocol ReportManager <NSObject>
- (void) report: (ReportReq *) req;  // throws TException
@end

@interface ReportManagerClient : NSObject <ReportManager> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ReportManagerProcessor : NSObject <TProcessor> {
id <ReportManager> mService;
NSDictionary * mMethodMap;
}
- (id) initWithReportManager: (id <ReportManager>) service;
- (id<ReportManager>) service;
@end

@interface shyConstants : NSObject {
}
@end
