/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


enum RESOURCE_TYPE {
  RESOURCE_TYPE_SONG = 0,
  RESOURCE_TYPE_CARTOON = 1,
  RESOURCE_TYPE_TV = 2,
  RESOURCE_TYPE_OTHER = 3
};

enum RESOURCE_SOURCE_TYPE {
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_YOUKU = 0,
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_56 = 1,
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_SOHU = 2,
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_SHY = 3,
  RESOURCE_SOURCE_TYPE_RESOURCE_SOURCE_OTHER = 100
};

@interface ReqHead : NSObject <TBase, NSCoding> {
  int32_t __babyId;
  NSString * __guid;
  NSString * __version;

  BOOL __babyId_isset;
  BOOL __guid_isset;
  BOOL __version_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=babyId, setter=setBabyId:) int32_t babyId;
@property (nonatomic, retain, getter=guid, setter=setGuid:) NSString * guid;
@property (nonatomic, retain, getter=version, setter=setVersion:) NSString * version;
#endif

- (id) init;
- (id) initWithBabyId: (int32_t) babyId guid: (NSString *) guid version: (NSString *) version;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) babyId;
- (void) setBabyId: (int32_t) babyId;
#endif
- (BOOL) babyIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) guid;
- (void) setGuid: (NSString *) guid;
#endif
- (BOOL) guidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) version;
- (void) setVersion: (NSString *) version;
#endif
- (BOOL) versionIsSet;

@end

@interface RegisterResp : NSObject <TBase, NSCoding> {
  int32_t __babyId;
  NSString * __pwd;
  int32_t __resCode;

  BOOL __babyId_isset;
  BOOL __pwd_isset;
  BOOL __resCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=babyId, setter=setBabyId:) int32_t babyId;
@property (nonatomic, retain, getter=pwd, setter=setPwd:) NSString * pwd;
@property (nonatomic, getter=resCode, setter=setResCode:) int32_t resCode;
#endif

- (id) init;
- (id) initWithBabyId: (int32_t) babyId pwd: (NSString *) pwd resCode: (int32_t) resCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) babyId;
- (void) setBabyId: (int32_t) babyId;
#endif
- (BOOL) babyIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pwd;
- (void) setPwd: (NSString *) pwd;
#endif
- (BOOL) pwdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) resCode;
- (void) setResCode: (int32_t) resCode;
#endif
- (BOOL) resCodeIsSet;

@end

@interface LoginReq : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSString * __pwd;

  BOOL __head_isset;
  BOOL __pwd_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=pwd, setter=setPwd:) NSString * pwd;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head pwd: (NSString *) pwd;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pwd;
- (void) setPwd: (NSString *) pwd;
#endif
- (BOOL) pwdIsSet;

@end

@interface LoginResp : NSObject <TBase, NSCoding> {
  int32_t __babyId;
  NSString * __uname;
  int32_t __resCode;

  BOOL __babyId_isset;
  BOOL __uname_isset;
  BOOL __resCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=babyId, setter=setBabyId:) int32_t babyId;
@property (nonatomic, retain, getter=uname, setter=setUname:) NSString * uname;
@property (nonatomic, getter=resCode, setter=setResCode:) int32_t resCode;
#endif

- (id) init;
- (id) initWithBabyId: (int32_t) babyId uname: (NSString *) uname resCode: (int32_t) resCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) babyId;
- (void) setBabyId: (int32_t) babyId;
#endif
- (BOOL) babyIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) uname;
- (void) setUname: (NSString *) uname;
#endif
- (BOOL) unameIsSet;

#if !__has_feature(objc_arc)
- (int32_t) resCode;
- (void) setResCode: (int32_t) resCode;
#endif
- (BOOL) resCodeIsSet;

@end

@interface ResourceInfo : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __url;
  NSString * __img;
  NSString * __title;
  int __resourceType;
  int __fileType;
  NSString * __desc;
  int32_t __durationTime;
  int32_t __releaseTime;
  int32_t __childAge;
  NSString * __language;
  NSString * __tags;
  int32_t __curSection;
  int32_t __SectionNum;
  NSString * __serialId;
  NSString * __vid;

  BOOL __id_isset;
  BOOL __url_isset;
  BOOL __img_isset;
  BOOL __title_isset;
  BOOL __resourceType_isset;
  BOOL __fileType_isset;
  BOOL __desc_isset;
  BOOL __durationTime_isset;
  BOOL __releaseTime_isset;
  BOOL __childAge_isset;
  BOOL __language_isset;
  BOOL __tags_isset;
  BOOL __curSection_isset;
  BOOL __SectionNum_isset;
  BOOL __serialId_isset;
  BOOL __vid_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=url, setter=setUrl:) NSString * url;
@property (nonatomic, retain, getter=img, setter=setImg:) NSString * img;
@property (nonatomic, retain, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, getter=resourceType, setter=setResourceType:) int resourceType;
@property (nonatomic, getter=fileType, setter=setFileType:) int fileType;
@property (nonatomic, retain, getter=desc, setter=setDesc:) NSString * desc;
@property (nonatomic, getter=durationTime, setter=setDurationTime:) int32_t durationTime;
@property (nonatomic, getter=releaseTime, setter=setReleaseTime:) int32_t releaseTime;
@property (nonatomic, getter=childAge, setter=setChildAge:) int32_t childAge;
@property (nonatomic, retain, getter=language, setter=setLanguage:) NSString * language;
@property (nonatomic, retain, getter=tags, setter=setTags:) NSString * tags;
@property (nonatomic, getter=curSection, setter=setCurSection:) int32_t curSection;
@property (nonatomic, getter=SectionNum, setter=setSectionNum:) int32_t SectionNum;
@property (nonatomic, retain, getter=serialId, setter=setSerialId:) NSString * serialId;
@property (nonatomic, retain, getter=vid, setter=setVid:) NSString * vid;
#endif

- (id) init;
- (id) initWithId: (int32_t) id url: (NSString *) url img: (NSString *) img title: (NSString *) title resourceType: (int) resourceType fileType: (int) fileType desc: (NSString *) desc durationTime: (int32_t) durationTime releaseTime: (int32_t) releaseTime childAge: (int32_t) childAge language: (NSString *) language tags: (NSString *) tags curSection: (int32_t) curSection SectionNum: (int32_t) SectionNum serialId: (NSString *) serialId vid: (NSString *) vid;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) url;
- (void) setUrl: (NSString *) url;
#endif
- (BOOL) urlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) img;
- (void) setImg: (NSString *) img;
#endif
- (BOOL) imgIsSet;

#if !__has_feature(objc_arc)
- (NSString *) title;
- (void) setTitle: (NSString *) title;
#endif
- (BOOL) titleIsSet;

#if !__has_feature(objc_arc)
- (int) resourceType;
- (void) setResourceType: (int) resourceType;
#endif
- (BOOL) resourceTypeIsSet;

#if !__has_feature(objc_arc)
- (int) fileType;
- (void) setFileType: (int) fileType;
#endif
- (BOOL) fileTypeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) desc;
- (void) setDesc: (NSString *) desc;
#endif
- (BOOL) descIsSet;

#if !__has_feature(objc_arc)
- (int32_t) durationTime;
- (void) setDurationTime: (int32_t) durationTime;
#endif
- (BOOL) durationTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) releaseTime;
- (void) setReleaseTime: (int32_t) releaseTime;
#endif
- (BOOL) releaseTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) childAge;
- (void) setChildAge: (int32_t) childAge;
#endif
- (BOOL) childAgeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) language;
- (void) setLanguage: (NSString *) language;
#endif
- (BOOL) languageIsSet;

#if !__has_feature(objc_arc)
- (NSString *) tags;
- (void) setTags: (NSString *) tags;
#endif
- (BOOL) tagsIsSet;

#if !__has_feature(objc_arc)
- (int32_t) curSection;
- (void) setCurSection: (int32_t) curSection;
#endif
- (BOOL) curSectionIsSet;

#if !__has_feature(objc_arc)
- (int32_t) sectionNum;
- (void) setSectionNum: (int32_t) SectionNum;
#endif
- (BOOL) SectionNumIsSet;

#if !__has_feature(objc_arc)
- (NSString *) serialId;
- (void) setSerialId: (NSString *) serialId;
#endif
- (BOOL) serialIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) vid;
- (void) setVid: (NSString *) vid;
#endif
- (BOOL) vidIsSet;

@end

@interface SearchReq : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSString * __searchKeys;
  int __resourceType;
  int32_t __startId;
  int32_t __recordNum;

  BOOL __head_isset;
  BOOL __searchKeys_isset;
  BOOL __resourceType_isset;
  BOOL __startId_isset;
  BOOL __recordNum_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=searchKeys, setter=setSearchKeys:) NSString * searchKeys;
@property (nonatomic, getter=resourceType, setter=setResourceType:) int resourceType;
@property (nonatomic, getter=startId, setter=setStartId:) int32_t startId;
@property (nonatomic, getter=recordNum, setter=setRecordNum:) int32_t recordNum;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head searchKeys: (NSString *) searchKeys resourceType: (int) resourceType startId: (int32_t) startId recordNum: (int32_t) recordNum;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSString *) searchKeys;
- (void) setSearchKeys: (NSString *) searchKeys;
#endif
- (BOOL) searchKeysIsSet;

#if !__has_feature(objc_arc)
- (int) resourceType;
- (void) setResourceType: (int) resourceType;
#endif
- (BOOL) resourceTypeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) startId;
- (void) setStartId: (int32_t) startId;
#endif
- (BOOL) startIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) recordNum;
- (void) setRecordNum: (int32_t) recordNum;
#endif
- (BOOL) recordNumIsSet;

@end

@interface SearchResp : NSObject <TBase, NSCoding> {
  NSMutableArray * __result;
  int32_t __resCode;

  BOOL __result_isset;
  BOOL __resCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=result, setter=setResult:) NSMutableArray * result;
@property (nonatomic, getter=resCode, setter=setResCode:) int32_t resCode;
#endif

- (id) init;
- (id) initWithResult: (NSMutableArray *) result resCode: (int32_t) resCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) result;
- (void) setResult: (NSMutableArray *) result;
#endif
- (BOOL) resultIsSet;

#if !__has_feature(objc_arc)
- (int32_t) resCode;
- (void) setResCode: (int32_t) resCode;
#endif
- (BOOL) resCodeIsSet;

@end

@interface RecommendReq : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  int32_t __startId;
  int32_t __recordNum;

  BOOL __head_isset;
  BOOL __startId_isset;
  BOOL __recordNum_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, getter=startId, setter=setStartId:) int32_t startId;
@property (nonatomic, getter=recordNum, setter=setRecordNum:) int32_t recordNum;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head startId: (int32_t) startId recordNum: (int32_t) recordNum;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (int32_t) startId;
- (void) setStartId: (int32_t) startId;
#endif
- (BOOL) startIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) recordNum;
- (void) setRecordNum: (int32_t) recordNum;
#endif
- (BOOL) recordNumIsSet;

@end

@interface RecommendResp : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSMutableArray * __recommends;
  int32_t __resCode;

  BOOL __head_isset;
  BOOL __recommends_isset;
  BOOL __resCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=recommends, setter=setRecommends:) NSMutableArray * recommends;
@property (nonatomic, getter=resCode, setter=setResCode:) int32_t resCode;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head recommends: (NSMutableArray *) recommends resCode: (int32_t) resCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) recommends;
- (void) setRecommends: (NSMutableArray *) recommends;
#endif
- (BOOL) recommendsIsSet;

#if !__has_feature(objc_arc)
- (int32_t) resCode;
- (void) setResCode: (int32_t) resCode;
#endif
- (BOOL) resCodeIsSet;

@end

@interface ResourcesReq : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSString * __name;
  NSString * __serialId;
  int32_t __startId;
  int32_t __recordNum;
  int __resourceType;

  BOOL __head_isset;
  BOOL __name_isset;
  BOOL __serialId_isset;
  BOOL __startId_isset;
  BOOL __recordNum_isset;
  BOOL __resourceType_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=serialId, setter=setSerialId:) NSString * serialId;
@property (nonatomic, getter=startId, setter=setStartId:) int32_t startId;
@property (nonatomic, getter=recordNum, setter=setRecordNum:) int32_t recordNum;
@property (nonatomic, getter=resourceType, setter=setResourceType:) int resourceType;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head name: (NSString *) name serialId: (NSString *) serialId startId: (int32_t) startId recordNum: (int32_t) recordNum resourceType: (int) resourceType;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) serialId;
- (void) setSerialId: (NSString *) serialId;
#endif
- (BOOL) serialIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) startId;
- (void) setStartId: (int32_t) startId;
#endif
- (BOOL) startIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) recordNum;
- (void) setRecordNum: (int32_t) recordNum;
#endif
- (BOOL) recordNumIsSet;

#if !__has_feature(objc_arc)
- (int) resourceType;
- (void) setResourceType: (int) resourceType;
#endif
- (BOOL) resourceTypeIsSet;

@end

@interface ResourceResp : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSMutableArray * __resList;
  int32_t __resCode;

  BOOL __head_isset;
  BOOL __resList_isset;
  BOOL __resCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=resList, setter=setResList:) NSMutableArray * resList;
@property (nonatomic, getter=resCode, setter=setResCode:) int32_t resCode;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head resList: (NSMutableArray *) resList resCode: (int32_t) resCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) resList;
- (void) setResList: (NSMutableArray *) resList;
#endif
- (BOOL) resListIsSet;

#if !__has_feature(objc_arc)
- (int32_t) resCode;
- (void) setResCode: (int32_t) resCode;
#endif
- (BOOL) resCodeIsSet;

@end

@interface ResourcesWatched : NSObject <TBase, NSCoding> {
  int32_t __resourceId;
  int32_t __durationTime;
  int32_t __sartTime;

  BOOL __resourceId_isset;
  BOOL __durationTime_isset;
  BOOL __sartTime_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=resourceId, setter=setResourceId:) int32_t resourceId;
@property (nonatomic, getter=durationTime, setter=setDurationTime:) int32_t durationTime;
@property (nonatomic, getter=sartTime, setter=setSartTime:) int32_t sartTime;
#endif

- (id) init;
- (id) initWithResourceId: (int32_t) resourceId durationTime: (int32_t) durationTime sartTime: (int32_t) sartTime;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) resourceId;
- (void) setResourceId: (int32_t) resourceId;
#endif
- (BOOL) resourceIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) durationTime;
- (void) setDurationTime: (int32_t) durationTime;
#endif
- (BOOL) durationTimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) sartTime;
- (void) setSartTime: (int32_t) sartTime;
#endif
- (BOOL) sartTimeIsSet;

@end

@interface ResourceSelected : NSObject <TBase, NSCoding> {
  NSString * __keyWords;
  NSMutableArray * __resourceIds;
  int32_t __chooseTime;

  BOOL __keyWords_isset;
  BOOL __resourceIds_isset;
  BOOL __chooseTime_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=keyWords, setter=setKeyWords:) NSString * keyWords;
@property (nonatomic, retain, getter=resourceIds, setter=setResourceIds:) NSMutableArray * resourceIds;
@property (nonatomic, getter=chooseTime, setter=setChooseTime:) int32_t chooseTime;
#endif

- (id) init;
- (id) initWithKeyWords: (NSString *) keyWords resourceIds: (NSMutableArray *) resourceIds chooseTime: (int32_t) chooseTime;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) keyWords;
- (void) setKeyWords: (NSString *) keyWords;
#endif
- (BOOL) keyWordsIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) resourceIds;
- (void) setResourceIds: (NSMutableArray *) resourceIds;
#endif
- (BOOL) resourceIdsIsSet;

#if !__has_feature(objc_arc)
- (int32_t) chooseTime;
- (void) setChooseTime: (int32_t) chooseTime;
#endif
- (BOOL) chooseTimeIsSet;

@end

@interface ReportReqs : NSObject <TBase, NSCoding> {
  ReqHead * __head;
  NSMutableArray * __watchRecord;
  NSMutableArray * __selectRecord;

  BOOL __head_isset;
  BOOL __watchRecord_isset;
  BOOL __selectRecord_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=head, setter=setHead:) ReqHead * head;
@property (nonatomic, retain, getter=watchRecord, setter=setWatchRecord:) NSMutableArray * watchRecord;
@property (nonatomic, retain, getter=selectRecord, setter=setSelectRecord:) NSMutableArray * selectRecord;
#endif

- (id) init;
- (id) initWithHead: (ReqHead *) head watchRecord: (NSMutableArray *) watchRecord selectRecord: (NSMutableArray *) selectRecord;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (ReqHead *) head;
- (void) setHead: (ReqHead *) head;
#endif
- (BOOL) headIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) watchRecord;
- (void) setWatchRecord: (NSMutableArray *) watchRecord;
#endif
- (BOOL) watchRecordIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) selectRecord;
- (void) setSelectRecord: (NSMutableArray *) selectRecord;
#endif
- (BOOL) selectRecordIsSet;

@end

@interface ResourceIds : NSObject <TBase, NSCoding> {
  NSMutableArray * __resourceList;

  BOOL __resourceList_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=resourceList, setter=setResourceList:) NSMutableArray * resourceList;
#endif

- (id) init;
- (id) initWithResourceList: (NSMutableArray *) resourceList;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) resourceList;
- (void) setResourceList: (NSMutableArray *) resourceList;
#endif
- (BOOL) resourceListIsSet;

@end

@interface ResourceInfoList : NSObject <TBase, NSCoding> {
  NSMutableArray * __infoList;
  int32_t __resCode;

  BOOL __infoList_isset;
  BOOL __resCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=infoList, setter=setInfoList:) NSMutableArray * infoList;
@property (nonatomic, getter=resCode, setter=setResCode:) int32_t resCode;
#endif

- (id) init;
- (id) initWithInfoList: (NSMutableArray *) infoList resCode: (int32_t) resCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSMutableArray *) infoList;
- (void) setInfoList: (NSMutableArray *) infoList;
#endif
- (BOOL) infoListIsSet;

#if !__has_feature(objc_arc)
- (int32_t) resCode;
- (void) setResCode: (int32_t) resCode;
#endif
- (BOOL) resCodeIsSet;

@end

@protocol UserManager <NSObject>
- (RegisterResp *) userRegister: (ReqHead *) req;  // throws TException
- (LoginResp *) login: (LoginReq *) req;  // throws TException
- (void) logout: (ReqHead *) req;  // throws TException
@end

@interface UserManagerClient : NSObject <UserManager> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface UserManagerProcessor : NSObject <TProcessor> {
  id <UserManager> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithUserManager: (id <UserManager>) service;
- (id<UserManager>) service;
@end

@protocol ResourceManager <NSObject>
- (SearchResp *) search: (SearchReq *) req;  // throws TException
- (RecommendResp *) getRecommendResources: (RecommendReq *) req;  // throws TException
- (ResourceResp *) getResources: (ResourcesReq *) req;  // throws TException
@end

@interface ResourceManagerClient : NSObject <ResourceManager> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ResourceManagerProcessor : NSObject <TProcessor> {
id <ResourceManager> mService;
NSDictionary * mMethodMap;
}
- (id) initWithResourceManager: (id <ResourceManager>) service;
- (id<ResourceManager>) service;
@end

@protocol ReportManager <NSObject>
- (void) tell: (ReportReqs *) req;  // throws TException
@end

@interface ReportManagerClient : NSObject <ReportManager> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ReportManagerProcessor : NSObject <TProcessor> {
id <ReportManager> mService;
NSDictionary * mMethodMap;
}
- (id) initWithReportManager: (id <ReportManager>) service;
- (id<ReportManager>) service;
@end

@protocol RecommendManager <NSObject>
- (int32_t) recommendAdd: (ResourceIds *) req;  // throws TException
- (int32_t) recommendDel: (ResourceIds *) req;  // throws TException
- (int32_t) recommendModify: (ResourceInfoList *) req;  // throws TException
- (ResourceInfoList *) getByids: (ResourceIds *) ids;  // throws TException
@end

@interface RecommendManagerClient : NSObject <RecommendManager> {
id <TProtocol> inProtocol;
id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface RecommendManagerProcessor : NSObject <TProcessor> {
id <RecommendManager> mService;
NSDictionary * mMethodMap;
}
- (id) initWithRecommendManager: (id <RecommendManager>) service;
- (id<RecommendManager>) service;
@end

@interface shy_serverConstants : NSObject {
}
@end
